DROP TABLE PROJECT;

DROP SEQUENCE SEQ_PNO; -- 프로젝트아이디를 발생시킬 시퀀스

----------------------------------------------------------------------------------------------------
-- PROJECT TABLE
----------------------------------------------------------------------------------------------------

CREATE TABLE PROJECT (
	PROJECT_ID VARCHAR2(30) PRIMARY KEY,
	-- FOREIGN KEY (CLIENT_ID) REFERENCES MEMBER(USER_ID),
	REQUIRED_SKILL VARCHAR2(400),
	PROJECT_NAME VARCHAR2(500) NOT NULL,
	DESCRIPTION VARCHAR2(4000) NOT NULL,
	PROJECT_STATUS VARCHAR2(10) DEFAULT 'OPEN' CHECK (PROJECT_STATUS IN('OPEN', 'START', 'PROCESS', 'HOLD', 'CLOSE', 'END', 'DELETE')),
	EXPECT_START DATE NOT NULL,
	EXPECT_END DATE NOT NULL,
	MEANS_OF_PAYMENT VARCHAR2(10) NOT NULL CHECK (MEANS_OF_PAYMENT IN('CREDIT', 'ACCOUNT')),
	MIN_BID NUMBER NOT NULL,
	MAX_BID NUMBER NOT NULL,
	START_BID DATE DEFAULT SYSDATE NOT NULL,
	END_BID DATE DEFAULT SYSDATE NOT NULL,
	COUNT_BID NUMBER,
	AVERAGE_BID NUMBER,
	WINNER_ID VARCHAR2(30),
	WINNING_BID NUMBER,
	START_DATE DATE DEFAULT SYSDATE,
	END_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN PROJECT.PROJECT_ID IS '프로젝트아이디';
-- COMMENT ON COLUMN PROJECT.CLIENT_ID IS '프로젝트의뢰인';
COMMENT ON COLUMN PROJECT.REQUIRED_SKILL IS '요구기술항목';
COMMENT ON COLUMN PROJECT.PROJECT_NAME IS '프로젝트명';
COMMENT ON COLUMN PROJECT.DESCRIPTION IS '프로젝트내용';
COMMENT ON COLUMN PROJECT.PROJECT_STATUS IS '상태값(OPEN/START/PROCESS/HOLD/CLOSE/END/DELETE)';
COMMENT ON COLUMN PROJECT.EXPECT_START IS '예상시작일';
COMMENT ON COLUMN PROJECT.EXPECT_END IS '예상마감일';
COMMENT ON COLUMN PROJECT.MEANS_OF_PAYMENT IS '지불수단(CREDIT/ACCOUNT)';
COMMENT ON COLUMN PROJECT.MIN_BID IS '최소호가';
COMMENT ON COLUMN PROJECT.MAX_BID IS '최대호가';
COMMENT ON COLUMN PROJECT.START_BID IS '입찰시작일';
COMMENT ON COLUMN PROJECT.END_BID IS '입찰마감일';
COMMENT ON COLUMN PROJECT.COUNT_BID IS '입찰수';
COMMENT ON COLUMN PROJECT.AVERAGE_BID IS '평균입찰가';
COMMENT ON COLUMN PROJECT.WINNER_ID IS '낙찰자';
COMMENT ON COLUMN PROJECT.WINNING_BID IS '낙찰가';
COMMENT ON COLUMN PROJECT.START_DATE IS '작업시작일';
COMMENT ON COLUMN PROJECT.END_DATE IS '작업마감일';

CREATE SEQUENCE SEQ_PNO
NOCACHE;

commit;

----------------------------------------------------------------------------------------------------