-- DROP ALL TABLES & SEQUENCE FOR THE FIRST TIME

DROP TABLE ENQUIRY;     -- 진섭
DROP TABLE REPORT;      -- 진섭
DROP TABLE FAQ;         -- 진섭
DROP TABLE PROPOSAL;
DROP TABLE PROJECT;
DROP TABLE MEMBER;

DROP SEQUENCE SEQ_PROJ;     -- 프로젝트아이디를 발생시킬 시퀀스
DROP SEQUENCE SEQ_PROP;     -- 작업제안번호를 발생시킬 시퀀스
DROP SEQUENCE SEQ_ENQ;      -- 1:1문의 발생시킬 시퀀스
DROP SEQUENCE SEQ_REPORT;   -- 신고번호 발생시킬 시퀀스
DROP SEQUENCE SEQ_FAQ;      -- FAQ 번호 발생시킬 시퀀스

--------------------------------------------------
--------------  MEMBER TABLE	------------------	
--------------------------------------------------

CREATE TABLE MEMBER (
	USER_ID	VARCHAR2(30) NOT NULL,
	USER_EMAIL	VARCHAR2(50) NOT NULL,
	USER_PWD	VARCHAR2(30) NOT NULL,
	ENROLL_DATE	DATE DEFAULT SYSDATE	NULL,
	OUTROLL_DATE DATE	NULL,
	STATUS	VARCHAR2(1)	DEFAULT 'Y'	NULL,
	MEMBERSHIP	VARCHAR2(1)	DEFAULT 'N'	NULL,
	EXCELLENT_FREELANCE	VARCHAR2(1)	DEFAULT 'N'	NULL,
	BLACKLIST	VARCHAR2(30)	DEFAULT 'N'	NULL,
	IDENTIFY_EMAIL	VARCHAR2(1)	DEFAULT 'N'	NULL,
	ADMIN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	USER_TYPE	VARCHAR2(1)	 NULL,
	JOB_TITLE	VARCHAR2(20) NULL,
	COMPANY	VARCHAR2(30) NULL,
	SKILL	VARCHAR2(400) NULL,
	PAY_RATE NUMBER NULL,
	PROFILE_IMAGE VARCHAR2(50) DEFAULT 'IMAGE' NOT NULL,
	LOCATION VARCHAR2(20) NULL
);

COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_EMAIL IS '회원이메일';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.OUTROLL_DATE IS '회원탈퇴일';
COMMENT ON COLUMN MEMBER.STATUS IS '처리상태(Y/N)';
COMMENT ON COLUMN MEMBER.MEMBERSHIP IS '처리상태(Y/N)';
COMMENT ON COLUMN MEMBER.EXCELLENT_FREELANCE IS '처리상태(Y/N)';
COMMENT ON COLUMN MEMBER.BLACKLIST IS '처리상태(Y/N)';
COMMENT ON COLUMN MEMBER.IDENTIFY_EMAIL IS '처리상태(Y/N)';
COMMENT ON COLUMN MEMBER.ADMIN IS '처리상태(Y/N)';
COMMENT ON COLUMN MEMBER.USER_TYPE IS '처리상태(프리랜서F/고용주E)';
COMMENT ON COLUMN MEMBER.JOB_TITLE IS '직급';
COMMENT ON COLUMN MEMBER.COMPANY IS '회사';
COMMENT ON COLUMN MEMBER.SKILL IS 'html,jsp,php';
COMMENT ON COLUMN MEMBER.PAY_RATE IS '희망 시급(원)';
COMMENT ON COLUMN MEMBER.LOCATION IS '서울,부산';

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	USER_ID
);

-- 회원, 관리자 Sample
INSERT INTO MEMBER(USER_ID, USER_EMAIL, USER_PWD, ADMIN)
VALUES ('admin', 'admin@gmail.com', '1234', 'Y');
INSERT INTO MEMBER(USER_ID, USER_EMAIL, USER_PWD, ADMIN, USER_TYPE, PROFILE_IMAGE)
VALUES ('user01', 'user01@gmail.com', '1234', 'N', 'F', '프로필이미지입니다.');

--------------------------------------------------
--------------  PROJECT TABLE	------------------	
--------------------------------------------------

CREATE TABLE PROJECT (
	PROJECT_ID VARCHAR2(30) PRIMARY KEY,
    CLIENT_ID VARCHAR2(30) NOT NULL,
	REQUIRED_SKILL VARCHAR2(400),
	PROJECT_NAME VARCHAR2(500) NOT NULL,
	DESCRIPTION VARCHAR2(4000) NOT NULL,
	PROJECT_STATUS VARCHAR2(10) DEFAULT 'OPEN' CHECK (PROJECT_STATUS IN('OPEN', 'START', 'PROCESS', 'HOLD', 'CLOSE', 'END', 'DELETE')),
	EXPECT_START DATE NOT NULL,
	EXPECT_END DATE NOT NULL,
	MEANS_OF_PAYMENT VARCHAR2(10) NOT NULL CHECK (MEANS_OF_PAYMENT IN('CREDIT', 'ACCOUNT')),
	MIN_BID NUMBER NOT NULL,
	MAX_BID NUMBER NOT NULL,
	START_BID DATE DEFAULT SYSDATE NOT NULL,
	END_BID DATE DEFAULT SYSDATE NOT NULL,
	COUNT_BID NUMBER,
	AVERAGE_BID NUMBER,
	WINNER_ID VARCHAR2(30),
	WINNING_BID NUMBER,
	START_DATE DATE DEFAULT SYSDATE,
	END_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN PROJECT.PROJECT_ID IS '프로젝트아이디';
COMMENT ON COLUMN PROJECT.CLIENT_ID IS '프로젝트의뢰인';
COMMENT ON COLUMN PROJECT.REQUIRED_SKILL IS '요구기술항목';
COMMENT ON COLUMN PROJECT.PROJECT_NAME IS '프로젝트명';
COMMENT ON COLUMN PROJECT.DESCRIPTION IS '프로젝트내용';
COMMENT ON COLUMN PROJECT.PROJECT_STATUS IS '상태값(OPEN/START/PROCESS/HOLD/CLOSE/END/DELETE)';
COMMENT ON COLUMN PROJECT.EXPECT_START IS '예상시작일';
COMMENT ON COLUMN PROJECT.EXPECT_END IS '예상마감일';
COMMENT ON COLUMN PROJECT.MEANS_OF_PAYMENT IS '지불수단(CREDIT/ACCOUNT)';
COMMENT ON COLUMN PROJECT.MIN_BID IS '최소호가';
COMMENT ON COLUMN PROJECT.MAX_BID IS '최대호가';
COMMENT ON COLUMN PROJECT.START_BID IS '입찰시작일';
COMMENT ON COLUMN PROJECT.END_BID IS '입찰마감일';
COMMENT ON COLUMN PROJECT.COUNT_BID IS '입찰수';
COMMENT ON COLUMN PROJECT.AVERAGE_BID IS '평균입찰가';
COMMENT ON COLUMN PROJECT.WINNER_ID IS '낙찰자';
COMMENT ON COLUMN PROJECT.WINNING_BID IS '낙찰가';
COMMENT ON COLUMN PROJECT.START_DATE IS '작업시작일';
COMMENT ON COLUMN PROJECT.END_DATE IS '작업마감일';

ALTER TABLE PROJECT ADD CONSTRAINT FK_MEMBER_TO_PROJECT_1 FOREIGN KEY (
	CLIENT_ID
)
REFERENCES MEMBER (
	USER_ID
);

CREATE SEQUENCE SEQ_PROJ
NOCACHE;

-- 프로젝트 샘플 데이터 
INSERT INTO PROJECT VALUES(SEQ_PROJ.NEXTVAL, 'user01', 'Java', 'Project 001', 'Project 001', DEFAULT, '2020-10-09', '2020-12-09', 'CREDIT', 2000000, 5000000, DEFAULT, '2020-10-08', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PROJECT VALUES(SEQ_PROJ.NEXTVAL, 'user01', 'Python', 'Project 002', 'Project 002', DEFAULT, '2020-10-09', '2020-12-09', 'CREDIT', 2000000, 5000000, DEFAULT, '2020-10-08', NULL, NULL, NULL, NULL, NULL, NULL);

--------------------------------------------------
--------------  PROPOSAL TABLE	------------------	
--------------------------------------------------

CREATE TABLE PROPOSAL (
	PROPOSAL_NO	NUMBER		NOT NULL,
	PROJECT_ID	VARCHAR2(30)	NOT NULL,
	USER_ID		VARCHAR2(30)	NOT NULL,
	PROPOSAL_STATUS	VARCHAR2(1)	DEFAULT 'N' NULL,
	PROPOSAL_INFO	VARCHAR2(4000)	NULL,
	PROPOSAL_PRICE	NUMBER		NULL,
	PROPOSAL_START	DATE		NULL,
	PROPOSAL_END	DATE		NULL
);

COMMENT ON COLUMN PROPOSAL.PROPOSAL_NO IS '작업제안번호';
COMMENT ON COLUMN PROPOSAL.PROJECT_ID IS '프로젝트아이디';
COMMENT ON COLUMN PROPOSAL.USER_ID IS '회원아이디';
COMMENT ON COLUMN PROPOSAL.PROPOSAL_STATUS IS '입찰승락여부(Y/N)';
COMMENT ON COLUMN PROPOSAL.PROPOSAL_INFO IS '작업제안내용';
COMMENT ON COLUMN PROPOSAL.PROPOSAL_PRICE IS '작업제안가';
COMMENT ON COLUMN PROPOSAL.PROPOSAL_START IS '입찰작업시작일';
COMMENT ON COLUMN PROPOSAL.PROPOSAL_END IS '입찰작업마감일';

ALTER TABLE PROPOSAL ADD CONSTRAINT PK_PROPOSAL PRIMARY KEY (
	PROPOSAL_NO
);

ALTER TABLE PROPOSAL ADD CONSTRAINT FK_PROJECT_TO_PROPOSAL_1 FOREIGN KEY (
	PROJECT_ID
)
REFERENCES PROJECT (
	PROJECT_ID
);

ALTER TABLE PROPOSAL ADD CONSTRAINT FK_MEMBER_TO_PROPOSAL_1 FOREIGN KEY (
	USER_ID
)
REFERENCES MEMBER (
	USER_ID
);

-- PROPOSAL 샘플데이터


CREATE SEQUENCE SEQ_PROP
NOCACHE;


--------------------------------------------------
----------  ENQUIRY(1:1문의) 진섭  ----------------	
--------------------------------------------------

CREATE TABLE ENQUIRY (
	INQ_NO	NUMBER PRIMARY KEY,   
	USER_ID	VARCHAR2(30)		NOT NULL,
	ENQUIRY_TYPE	VARCHAR2(100)		NOT NULL,
	ENQUIRY_TITLE	VARCHAR2(300)		NOT NULL,
	ENQUIRY_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	ENQUIRY_CONTENT	VARCHAR2(2000)		NOT NULL,
	ANSWER_CONTENT	VARCHAR2(2000)		NULL,
	ANSWER_STATE	VARCHAR2(1) DEFAULT 'Y' CHECK (ANSWER_STATE IN('Y', 'N')),
	ANSWER_DATE	DATE	DEFAULT SYSDATE
);

COMMENT ON COLUMN ENQUIRY.USER_ID IS '회원아이디';
COMMENT ON COLUMN ENQUIRY.ENQUIRY_TYPE IS '문의유형';
COMMENT ON COLUMN ENQUIRY.ENQUIRY_TITLE IS '문의제목';
COMMENT ON COLUMN ENQUIRY.ENQUIRY_DATE IS '문의일자';
COMMENT ON COLUMN ENQUIRY.ENQUIRY_CONTENT IS '문의내용';
COMMENT ON COLUMN ENQUIRY.ANSWER_CONTENT IS '답변내용';
COMMENT ON COLUMN ENQUIRY.ANSWER_STATE IS '처리여부(Y/N)';
COMMENT ON COLUMN ENQUIRY.ANSWER_DATE IS '답변날짜';

ALTER TABLE ENQUIRY ADD CONSTRAINT FK_MEMBER_TO_ENQUIRY_1 FOREIGN KEY (
	USER_ID
)
REFERENCES MEMBER (
	USER_ID
);

CREATE SEQUENCE SEQ_ENQ
NOCACHE;

-- ENQ 샘플데이터


--------------------------------------------------
-------------- REPORT(신고) 진섭	------------------	
--------------------------------------------------

CREATE TABLE REPORT (
	REPORT_NO	NUMBER PRIMARY KEY,
	REPORTER_ID	VARCHAR2(30)		NOT NULL,
	DEFENDANT_ID	VARCHAR2(30)		NULL,
	PROJECT_ID	VARCHAR2(30)		NULL,
	REPORT_CATEGORY	VARCHAR2(100)		NOT NULL,
	REPORT_TITLE	VARCHAR2(200)		NOT NULL,
	REPORT_CONTENT	VARCHAR2(2000)		NOT NULL,
	REPORT_TARGET	VARCHAR2(1)		NOT NULL,
	REPORT_DATE	DATE		NOT NULL,
	REPORT_STATUS	VARCHAR2(1) DEFAULT 'Y' CHECK(REPORT_STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN REPORT.REPORTER_ID IS '신고신청자아이디';
COMMENT ON COLUMN REPORT.DEFENDANT_ID IS '신고대상자아이디';
COMMENT ON COLUMN REPORT.PROJECT_ID IS '신고프로젝트아이디';
COMMENT ON COLUMN REPORT.REPORT_CATEGORY IS '신고위반사항';
COMMENT ON COLUMN REPORT.REPORT_TITLE IS '신고제목';
COMMENT ON COLUMN REPORT.REPORT_CONTENT IS '신고내용';
COMMENT ON COLUMN REPORT.REPORT_TARGET IS '신고대상';
COMMENT ON COLUMN REPORT.REPORT_DATE IS 'SYSDATE';
COMMENT ON COLUMN REPORT.REPORT_STATUS IS '상태여부(Y/N)';

ALTER TABLE REPORT ADD CONSTRAINT FK_MEMBER_TO_REPORT_1 FOREIGN KEY (
	REPORTER_ID
)
REFERENCES MEMBER (
	USER_ID
);

ALTER TABLE REPORT ADD CONSTRAINT FK_MEMBER_TO_REPORT_2 FOREIGN KEY (
	DEFENDANT_ID
)
REFERENCES MEMBER (
	USER_ID
);

ALTER TABLE REPORT ADD CONSTRAINT FK_PROJECT_TO_REPORT_1 FOREIGN KEY (
	PROJECT_ID
)
REFERENCES PROJECT (
	PROJECT_ID
);

CREATE SEQUENCE SEQ_REPORT
NOCACHE;

-- REPORT 샘플데이터


--------------------------------------------------
--------------      FAQ(진섭) 	------------------	
--------------------------------------------------

CREATE TABLE FAQ (
	FAQ_NO	NUMBER PRIMARY KEY,
	FAQ_CATEGORY	VARCHAR2(100)		NOT NULL,
	FAQ_TITLE	VARCHAR2(200)		NOT NULL,
	FAQ_CONTENT	VARCHAR2(2000)		NULL,
	FAQ_COUNT	NUMBER		NULL,
	FAQ_STATE	VARCHAR2(1) DEFAULT 'Y' CHECK(FAQ_STATE IN('Y', 'N')),
	FAQ_REGISTER	DATE	DEFAULT SYSDATE	NOT NULL,
	FAQ_UPDATE	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN FAQ.FAQ_NO IS 'FAQ번호';
COMMENT ON COLUMN FAQ.FAQ_CATEGORY IS 'FAQ카테고리';
COMMENT ON COLUMN FAQ.FAQ_TITLE IS 'FAQ제목';
COMMENT ON COLUMN FAQ.FAQ_CONTENT IS 'FAQ세부내용';
COMMENT ON COLUMN FAQ.FAQ_COUNT IS 'FAQ조회수';
COMMENT ON COLUMN FAQ.FAQ_STATE IS '공개여부(Y/N)';
COMMENT ON COLUMN FAQ.FAQ_REGISTER IS 'FAQ등록일';
COMMENT ON COLUMN FAQ.FAQ_UPDATE IS 'FAQ수정일';

CREATE SEQUENCE SEQ_FAQ
NOCACHE;

-- FAQ 샘플데이터


----------------------------------------------------------------------------------------------------

COMMIT;